### ISSUE TITLE
fish points and key features from our sampling. There is an object that we produce with `scripts/outgoing_mapping` that we can use for this

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_elk_2022_reporting#35]

**Comment by NewGraphEnvironment** [comment]
good question but no - not yet - not for this report at this time.  

There is an object that we already create for fish points. It gives species as an array at the survey site start location. That will be good enough for now.

**Comment by Mateo9569** [comment]
Gotcha, I know the object you're talking about. There were a few fish caught where the species could not be identified. Am including those in the fish points or filtering them out?

**Comment by NewGraphEnvironment** [comment]
species code for unknown is `SP`.  were the fish actually captured or were they visual observations (VO)?  Regardless, no need to filter them out if they are in there already

**Comment by NewGraphEnvironment** [comment]
> Are you referring to the `hab_features` object?

` hab_fish_collect`

**Comment by NewGraphEnvironment** [comment]
actually the fish are not an array. they were when I first made the object back in the day but I changed that to make them one species occurrence per row I guess...

**Comment by NewGraphEnvironment** [comment]
this object was mangled.  I wonder if it is mangled in all our repos?

there are tons of features detailed in step 4 of the hab con spreadsheet without coordinates and some features that do not even have a`Feature Type` defined. We should log issues like this and amybe record initials of who did the assessments in the comments so that we know who to follow up with to try to find the information. Sometimes we might need to pull wack data but we should track what is going on in issues and educate collaborators on what is happening and why

**Comment by Mateo9569** [comment]
Ya the features are a bit mangled. They were fine in the bulkley repo because there wasn't that many and I was able to get utms. Rest of the repos not so much. Remember I tried making a script for this a little while ago? Referenced [here](https://github.com/NewGraphEnvironment/fish_passage_skeena_2022_reporting/issues/61). Also you mentioned that this stuff might be best left to you, because you've had troubles with it in the past (see comment [here](https://github.com/NewGraphEnvironment/fish_passage_skeena_2022_reporting/pull/64#discussion_r1103129934)). Regardless, I did kind of forget about the features here, my bad. I could fill in the utms by linking to tracks where possible by hand for elk and parsnip too but we should figure out a better way to do it for the skeena.

**Comment by NewGraphEnvironment** [comment]
Ya - best to file an issue at the start when it comes up since it is a new repo. otherwise its easy to miss and/or forget. 

Have a close look at what all those features are and make a judgement call whether logging them is helpful. We only need to log really significant features and those with complete information. If it wasn't me or you who added them, be discerning and look at the sites that I did as examples of the types of things that get logged (none or very rare?). We don't want to litter the provincial database with a million debris jams. Steep streams have debris jams and imagine what our field maps would look like if all of them went into the system. We would have to throw that layer away

An important one to put in that likely isn't there is the dewatering from Dom and Ariana's site way up in Weigert. That point tells a story not yet told

**Comment by Mateo9569** [comment]
That's a good point, I can't imagine what the provincial database would look like if every little obstacle was uploaded. So I guess there's no specific cutoff value for minimum height of a feature that qualifies as an obstacle. Obviously there's a few factors at play. I'll try to make judgement calls. 

Would I input a length for a dewatering feature? So an estimate of the length of stream that's dewatered. And the UTM would be at the bottom of the dewatered section?

**Comment by NewGraphEnvironment** [comment]
> this object was mangled. I wonder if it is mangled in all our repos?

I was refering to the `hab_fish_collect` object.  It was grouping all the sites by site_us and site_ds only so loosing the detail of all the individual electrofishing sites.  Additionally it was not including `NFC` with a note as to why (multiplass electrofishing in closed sites) and to "watch for this in the future" . In the elk there were only 3 sites shown vs the 6 that should have been there. Need to inspect objects before burning to the geopackages so that we QA the data we put on the street and catch issues sooner than later

**Comment by Mateo9569** [comment]
Ok, I'll change it in the other repos. To be honest I thought it was supposed to group sites by upstream and downstream, it was like that in last years skeena repo too. I didn't know that was wrong. Now I do, thanks.

**Comment by Mateo9569** [comment]
Closed via https://github.com/NewGraphEnvironment/fish_passage_elk_2022_reporting/commit/6c47371bcc33f86339daf54eca1d5fb61a76aace
