### ISSUE TITLE
Fix squished x axis on hydrology stat graphs (Figures 2.3 and 2.4)

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_elk_2022_reporting#51]

**Comment by NewGraphEnvironment** [comment]
this is a very deep can of worms because it is spelled out inside of a function. I have addressed this issue before in this fork of `fasstr` .  https://github.com/NewGraphEnvironment/fasstr/tree/NewGraph in this custom function https://github.com/NewGraphEnvironment/fasstr/blob/NewGraph/R/plot_data_screening2.R

Let's not prioritize this right away.  Best way to deal is probably to build the package locally (ie. `git clone`) from the one on my github page - switch to `newgraph` branch and rebuild the plots with `plot_data_screening2` or `plot_data_screening3`. Might not be a simple process though for any number of reasons. Several of them related to how old that branch is and all the changes that would have happeneed to dependencies packages since it was last run
