### ISSUE TITLE
Need to hack fish summary script to account for visual observations without lengths

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_elk_2022_reporting#7]
There are two entries in electrofishing data for Weigert Creek site 197534_us_ef6 where there was a visual observation and no lengths were estimated. Ariana and the other guy who's name is eluding me right now did this site. Maybe they saw the fish briefly or it was too far away to get a good length estimate.

**Comment by Mateo9569** [comment]
I'll just do a `case_when` so that these observations still show up in step 2. I'll write in the comments that lengths couldn't be estimated or something like that

**Comment by NewGraphEnvironment** [comment]
Good idea. Important to watch that the VO still show up in the mapping geopackage too because sometimes it shows presence on the hillcrest served maps where otherwise the reader would not be aware that we know there are fish there. Check older repos like the Bulkley 2020 and elk 2020 and elk 2021 for examples of VO processing as I’m sure VO has been filtered out before and there might be other moves to also have them show in the gpkg. A find in file search for “vo” might bear fruit
